version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mindbox_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    environment:
      - IS_DJANGO=True
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: mindbox_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres
